dist: trusty
sudo: required

services:
  - docker

before_install:
  - git clone https://github.com/probcomp/nginx-proxy.git
  - git clone https://github.com/probcomp/bayesrest.git
  - pushd bayesrest
  - git checkout falcon-refactor
  - cp config-example.yaml config.yaml
  - popd
  - cp database.bdb bayesrest
script:
  - make test
after_script:
  - docker-compose down
