dist: trusty
sudo: required

services:
  - docker

before_install:
  - git clone https://github.com/probcomp/nginx-proxy.git
  - pushd nginx-proxy
  - popd
  - git clone https://github.com/probcomp/bayesrest.git
  - pushd bayesrest
  - git checkout falcon-refactor
  - cp config-example.yaml config.yaml
  - popd
  - docker-compose up
script:
  - curl http://localhost:5000/not-found
after_script:
  - docker-compose down
