dist: trusty
sudo: required

services:
  - docker

before_install:
  # https://docs.travis-ci.com/user/customizing-the-build/#Authentication
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - git clone https://github.com/probcomp/nginx-proxy.git
  - git clone https://github.com/probcomp/bayesrest.git
  - pushd bayesrest
  - git checkout falcon-refactor
  - cp config-example.yaml config.yaml
  - popd
  - cp database.bdb bayesrest
script:
  - make test
after_script:
  - docker-compose down

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: NtrvT5cxmlijcErKQxEilOfVNWXUoJCuJcmH8w2QRwlMj/zV1/tb5SJflsBKp9CrpRdvTiiP+CLu+jy1GOD72mDg49VSsizx05dNiLBCOPPsLyFjLwBbgTWI+LFUHHIBDuKQoskQVcoAi19S/F9jdhD1olNI9JIj6cZ6LkXgKHjNPAlsw847sk6/n5555B5KXyGAFLvJ8t10TXeaLCxnMo3mNEMwWWJLdkV1sB2JeYtdSR782TNCRnlz0ooIS0KxMeVExsdREoCSxHKosHn6ugR4JJv/SHoqLwOMmR2hhLlf2Xb9iDVCw4XoSsI0tLovYU6lyxU4G03PXoDx4ZUaqVlDSlqR8BtMTzdi/683csYgJCdb3OX5aCNpAZf4JMoPpiQDvFSXvvptJjy8EVkTKyS+fFK1P1r5vuQRTLADwNi92JyORhovslRSvAa2b5W+6rkdIfeCQWztJoozH8oNm2sl/cuFXtFfrZOauqhZc7URiROQreF7I40MfkmFxUqlSPOa2eRZ6r6azkL1bDWoa/WLIYyjzF9P1kB7TpVUMOur1dQRr0C18xIpoq518F7jXwch8sfZh2Mb/NmIZs4qp03eXRju11vltTScUCXWBXQ5AZnFcL9TR/SzGcPwEldsKneR2rN9j5pzNySt0owX7yozHxMf0mIsDWaggiOxQzM=
