dist: trusty
sudo: required

services:
  - docker

before_install:
  # https://docs.travis-ci.com/user/customizing-the-build/#Authentication
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
  - make extract
script:
  - make test
after_script:
  - docker-compose down

notifications:
  slack:
    secure: kHvexj2xepmJTovZBiBa+LFdBgZHdpByQTxUqM2bBIs73iCNrVUU/M1k1My1wFr3pi8OohDIIeZgjIAm043VlkiS3nKkTyFUw17ZdjlD03qlQsVD/v82TGv2jfaxKO7bS75wZ4iyx9VAJL+SFStvl95JxnfiH/9qyPQD9VRKY2/rrno6hqC/kKlgIt3j3CreNM+HVpp04JV0fkbY2t31hE2gsJHKrC8Ktj9Jrk204I/Y2M9Ru+P+AdJxMEO53MJIvdcCDlcy5m4kth8DQ8BsBcuzuinj41gtbLgqxwd03NDmconCKRwDLflLRBs68rt00BLl6+EKWXlmZF5gLd2+aFCww0bk6zi1nlHIeVMW8J6J7SlnVkE5miYqfr03rEUDBsvtCigjYWpVwH8c4LEpdvUIhQ5J3XkUh9AAAlYMTrQ72zWfG5Qzyj31Tmy+/yvCXMAxVjbIuNeOrootlUYKAQErf69uAO0DOwG/EqrHfULHP/+dhHhd+lyCkGDODbHQsRFjpjvinGqJkcRV+4JsEatviF6JMCbp3+3LPg7RxLakHVPu54k4cX4AbDVukAPAiEXxDxBYiCTyG0mkouQnyPBEcv5PcPYOmz66SKoBomI2SBQylc9OEAqnjZQPoO5w73vXKbE+JvSNwiVKXmvvKp9jFhXKJB9JG6gNSA8vMlk=
