version: "3"

networks:
  probcomp:
volumes:
  dhparam:
    driver: local

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.6.0
    networks:
      - probcomp
    environment:
      CERT_NAME: probcomp.dev
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - dhparam:/etc/nginx/dhparam:rw
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  bayesrest:
    working_dir: "/app"
    image: probcomp/bayesrest
    networks:
      - probcomp
    user: root
    environment:
      NB_UID: ${NB_UID}
      PYTHONPATH: '/app'
      CONFIG_FILE_PATH: '/app/config-example.yaml'
      BDB_FILE: '/app/bdb/counties_v6.bdb'
      TABLE_NAME: 'data'
      POPULATION_NAME: 'data'
      BACKEND: 'loom'
      LOOM_PATH: '/app/loom/'
    volumes:
      - ./bdb:/app/bdb
      - ./loom/loom-model-files-counties-v6:/app/loom
    ports:
      - "5000:5000"
  notebook:
    build: .
    networks:
      - probcomp
    ports:
      - "8888:8888"
    user: root
    environment:
      NB_UID: ${NB_UID}
    volumes:
      - ./work:/home/jovyan/work
    depends_on:
      - bayesrest
      - nginx-proxy
