version: "3"

networks:
  probcomp:
volumes:
  dhparam:
    driver: local

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:0.6.0
    networks:
      - probcomp
    environment:
      CERT_NAME: probcomp.dev
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - dhparam:/etc/nginx/dhparam:rw
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  bayesrest:
    working_dir: "/app"
    build:
      context: ./bayesrest
    networks:
      default:
      probcomp:
        aliases:
          - bayesapi
    environment:
      PYTHONPATH:
        '/app'
    volumes:
      - ./bayesrest:/app:cached
    ports:
      - "5000:5000"

  counties-demo:
    image: jupyter/minimal-notebook:92fe05d1e7e5
    networks:
      probcomp:
