version: "3"

networks:
  probcomp:
volumes:
  dhparam:
    driver: local

services:
  bayesrest:
    working_dir: "/app"
    build: ../bayesrest
    networks:
      - probcomp
    user: root
    environment:
      NB_UID: ${NB_UID}
      PYTHONPATH: '/app'
      CONFIG_FILE_PATH: '/app/config-example.yaml'
      BDB_FILE: '/app/bdb/counties_v6.bdb'
      TABLE_NAME: 'data'
      POPULATION_NAME: 'data'
      BACKEND: 'loom'
      LOOM_PATH: '/app/loom/'
    volumes:
      - ../bayesrest:/app
      - ./bdb:/app/bdb
      - ./loom/loom-model-files-counties-v6:/app/loom
    ports:
      - "5000:5000"
